# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
  schedule: 
  - cron:  '*/15 * * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run script
      env:
        INPUT_TOKEN: ${{ secrets.PAT }}
      run: |
        node runner.js
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic changes
